### PR TITLE
Edit and Assign nurse feature bug

### LINKED ISSUE #194: Fix edit feature bugs
Currently, the edit function allows these bugs:
- allows nurse to change appointment to a patient even when they have a patient assigned
- allows nurse to change name even when they have a patient assigned
- allows patient to change appointment to a nurse even when they have a nurse assigned

### PR DESCRIPTION
**Pull request by jon-seana**
Fixes made for EditCommand.java:
- Ensure that a nurse can only change appointment to a patient if they have no patients assigned
- Ensure that a nurse can only change a name if they have no patients assigned
- Ensure that a patient can change to a nurse if they have no assigned nurse
- If any of the above 4 checks are violated, an error message will be shown.

Fixes #194

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/EditCommand.java [hunk 1]
```diff
@@ -103,6 +114,15 @@ public CommandResult execute(Model model) throws CommandException {
 
         ensureOnlyPatientCanHaveMedicalHistory(editedPerson);
 
+        if (editPersonDescriptor.getAppointment().isPresent()) {
+            ensurePatientHasNoAssignedNurse(personToEdit, model);
+            ensureNurseHasNoPatient(personToEdit, editedPerson, model);
+        }
+
+        if (editPersonDescriptor.getName().isPresent()) {
+            ensureChangeNameNurseIfNoPatient(personToEdit, model);
```
Comment (Shanyey) [inline src/main/java/seedu/address/logic/commands/EditCommand.java:123]: Good naming so that the reader can understand what is happening easily

**Review by Shanyey — APPROVED** [review]
