### PR TITLE
fix add command sample format

### LINKED ISSUE #173: [ADD] name can be stored as all numbers
Name as 12345 is accepted by the system
Image

### LINKED ISSUE #174: [ADD] Trailing whitespaces are not cleared in the name
n/1                          1 is accepted and stored
Image

### LINKED ISSUE #175: [ADD] Command descriptor can be clearer
Image
Should inform users that the fields in square brackets are optional

### LINKED ISSUE #200: [ADD] Fix bugs
Fix command descriptor clarity

Fix whitespaces in name

Fix numbers in name

### PR DESCRIPTION
**Pull request by Shanyey**
fix name alphabetical, repeated whitespaces

fix test cases

closes #200 
closes #175 
closes #174 
closes #173

### CODE REVIEW

File: src/test/java/seedu/address/model/person/PersonTest.java [hunk 1]
```diff
@@ -40,10 +40,10 @@ public void isSamePerson() {
 
         Person editedBob = new PersonBuilder(BOB).withName(VALID_NAME_BOB.toLowerCase()).build();
 
-        // name has trailing spaces, all other attributes same -> returns false
+        // name has trailing spaces, all other attributes same -> returns true
         String nameWithTrailingSpaces = VALID_NAME_BOB + " ";
         editedBob = new PersonBuilder(BOB).withName(nameWithTrailingSpaces).build();
-        assertFalse(BOB.isSamePerson(editedBob));
+        assertTrue(BOB.isSamePerson(editedBob));
```
Comment (jon-seana) [inline src/test/java/seedu/address/model/person/PersonTest.java:46]: Well done for keeping the test cases passing!
