### PR TITLE
Branch pe dry-run bugs fix

### LINKED ISSUE #287: [PE-D][Tester A] Patients with the same name are not allowed
When attempting to add another patient with the following command `add n/John Doe dob/01/01/2002 p/12341234 e/johnd@example.com a/1, yishun 2, #02-25 b/AB+ ap/Patient nok/bob 12345678 t/happy mh/High Blood Pressure`, the patient is rejected as it is flagged as being already existing in the list:

This may be a common issue as there are certain name combinations especially in Singapore which are extremely common, e.g John Tan, Ryan Tay etc.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: Fieash/ped#9

### LINKED ISSUE #290: [PE-D][Tester E] Find command can lead to misleading results if user makes a typo.
Currently find command allows for non-alphabetical symbols as arguments.
If a user makes a typo when using `find nurse of patient` or `find patient of nurse`, such as `find nurse of pateint 1`, it will taken as a `find` command with keyword argument of `nurse of pateint 1`, which will return an empty list.

This could cause the user to not notice their typo and think that patient 1 has no nurses regardless of if that's the case.

In addition, this makes it more difficult for the app to tell the user if they've made a formatting/input error when using `find patient of nurse` or `find nurse of patient` commands, since a wrong typo/format issue can be misinterpreted as a search keyword.

Some suggestions:
Perhaps you could try making command words joined together like `findpatientofnurse` or `find_patient_of_nurse`, or make use of the exiting prefix system, something like `find n/KEYWORD`, `find nurse/PATIENT_INDEX`, `find patient/NURSE_INDEX`

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: potatodudedude/ped#5

### LINKED ISSUE #309: [PE-D][Tester E] UG-Bug : Not enough images
There are only two images present currently in the UG.
I think certain more complicated commands like scheduling and finding nurse of patient/finding patient of nurse could do with some demo images.

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: potatodudedude/ped#7

### LINKED ISSUE #311: [PE-D][Tester E] Scheduling feature seems not developed enough to help the target audience
The UG says that the app "empowers private nurse centers to assign staff, retrieve patient information, and manage appointments". 

The current scheduling feature allows for recording of date and time of the meeting, but it has a few shortcomings. It does not record what the checkup is for, or how long it will take. There is currently no feature to allow assignment of nurses to a checkup slot, and hence also no feature to check if a nurse has any time conflict between slots. 

This means the clinic has to ultimate still manually check and assign nurses to checkups in order to be able to account for nurse availability and time conflicts.

I think a way to improve this would be to record which nurse(s) are responsible for which checkup, and prevent them from being able to attend any other checkup during that timeframe.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: potatodudedude/ped#9

### LINKED ISSUE #317: [PE-D][Tester A] Date of birth in the future allowed
As a Nurse inputting dates, a misinput of dates in the future for date of birth, which is not possible, is not caught and blocked.

after `edit 1 dob/01/01/2026`

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: Fieash/ped#16

### PR DESCRIPTION
**Pull request by chanjunlin**
Fix the bugs alerted to us in the PE dry-run

close #317
close #311 
close #309 
close #290 
close #287

### CODE REVIEW

File: src/main/java/seedu/address/model/person/DateOfBirth.java [hunk 1]
```diff
@@ -15,6 +15,7 @@
 public class DateOfBirth {
     public static final String MESSAGE_CONSTRAINTS = "Date Of Birth can only take the format:"
             + "DD/MM/YYYY";
+    public static final String FUTURE_DOB = "Date Of i cannot be in the future!";
```
Comment (Shanyey) [inline src/main/java/seedu/address/model/person/DateOfBirth.java:18]: What is date of i

Comment (chanjunlin) [reply src/main/java/seedu/address/model/person/DateOfBirth.java]: Oops, i've fixed it to display the proper string 😄
