### PR TITLE
Fix Bugs in ScheduleCommand and Enhance Test Coverage

### LINKED ISSUE #155: [Schedule] (bug) Cannot delete a checkup after date has passed
Cannot delete a checkup for a patient once the date/time has passed.

### LINKED ISSUE #157: [Schedule] (suggestion) Friendlier schedule command format (add on"for patient")
To change the schedule command format from (current) to (new):

(current) -> "schedule add 1 03/12/2025 1130"

(new) -> "schedule add for patient 1 03/12/2025 1130"

(current) -> "schedule delete 1 03/12/2025 1130"

(new) -> "schedule delete for patient 1 03/12/2025 1130"

### LINKED ISSUE #158: [Schedule] (bug) Checkup allowed for patient without nurse assigned
Current implementation allows for schedule of checkup for patients without nurse, perhaps a warning message can be shown to user when they decide to add a checkup for patients without a nurse, with this warning message "Check up has been created for a patient without a nurse, REMEMBER to assign a nurse promptly after this!”

### LINKED ISSUE #159: [Schedule] (suggestion) Add more comprehensive error message
Perhaps can add more comprehensive error message for scenarios like this (shown in the attached image) where the error message could be "please include add or delete after schedule"

Image

### PR DESCRIPTION
**Pull request by chanjunlin**
This pull request addresses and resolves several bugs identified in the ScheduleCommand class. It includes the following key changes:

- Bug Fixes:

  - Allow user to delete checkup for a date that has already passed (close #155)
  - Add user-friendly schedule commands (close #157)
  - Allow user to schedule checkup for a patient with no assigned nurse (close #158)
  - Add more comprehensive error message for schedule (close #159)

- Test Cases: added unit tests to verify the stability and correctness of the bug fixes.

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/ScheduleCommand.java [hunk 1]
```diff
@@ -154,20 +157,88 @@ private void hasTargetCheckup(Set<Checkup> patientCheckups, Checkup newCheckup)
...
+     *
+     * @param patient The patient whose tags will be checked for nurse assignments.
+     * @return True if the patient has at least one nurse assigned; false otherwise.
+     */
+    public boolean checkNurseAssignment(Person patient) {
+        List<String> nurseList = patient.getTags().stream()
+                .filter(tag -> tag.tagName.startsWith("Nurse"))
+                .map(tag -> tag.tagName.substring(5))
+                .collect(Collectors.toList());
+        return !nurseList.isEmpty();
```
Comment (Shanyey) [inline src/main/java/seedu/address/logic/commands/ScheduleCommand.java:242]: Good addition to check if the patient has a nurse assigned

File: src/main/java/seedu/address/model/checkup/Checkup.java [hunk 2]
```diff
@@ -25,6 +25,7 @@ public class Checkup {
     private static final LocalTime START_TIME = LocalTime.of(9, 0);
     private static final LocalTime END_TIME = LocalTime.of(17, 0);
     public final LocalDateTime checkupDateTime;
+    public final Boolean isAdding;
```
Comment (Shanyey) [inline src/main/java/seedu/address/model/checkup/Checkup.java:28]: Good way to track status + correct naming of boolean values

File: src/main/java/seedu/address/storage/JsonAdaptedCheckup.java [hunk 3]
```diff
@@ -52,6 +52,6 @@ public Checkup toModelType() throws IllegalValueException {
         LocalDate checkupDate = LocalDate.parse(date, DateTimeFormatter.ofPattern("dd/MM/yyyy"));
         LocalTime checkupTime = LocalTime.parse(time, DateTimeFormatter.ofPattern("HH:mm"));
 
-        return new Checkup(checkupDate, checkupTime);
+        return new Checkup(checkupDate, checkupTime, true);
```
Comment (Shanyey) [inline src/main/java/seedu/address/storage/JsonAdaptedCheckup.java:55]: not Covered by tests

**Review by Shanyey — APPROVED** [review]
