### PR TITLE
Fix error messages for "view" command

### LINKED ISSUE #189: Fix error message for "view" command
The error message is not shown correctly for the view command, and should be fixed to show the correct error message.

### PR DESCRIPTION
**Pull request by charlenelau-20**
Previously, some input cases for the view command were not handled properly, resulting in the wrong error message being shown to the user. This issue has been fixed to handle such input cases correctly.

Closes #189

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/ViewCommandParser.java [hunk 1]
```diff
@@ -20,9 +22,16 @@ public class ViewCommandParser implements Parser<ViewCommand> {
     public ViewCommand parse(String args) throws ParseException {
         try {
             String[] splitArgs = args.trim().split("\\s");
-            if (splitArgs.length != 1) {
-                throw new ParseException("Usage: view INDEX");
+            if (splitArgs.length != 1 || splitArgs[0].isEmpty()) {
+                throw new ParseException(String.format(MESSAGE_INVALID_COMMAND_FORMAT, ViewCommand.MESSAGE_USAGE));
```
Comment (jon-seana) [inline src/main/java/seedu/address/logic/parser/ViewCommandParser.java:26]: Good code neatness!
