### PR TITLE
fix list check up function

### LINKED ISSUE #92: Implement view schedules feature
This feature will allow the user to view all the checkup schedules currently added, or view the checkups for a certain nurse or patient

### PR DESCRIPTION
**Pull request by Shanyey**
Added sorting by earliest checkup while normal list is sorted by alphabetical order

Stored all names in full capital letter for better sorting

closes #92

### CODE REVIEW

File: src/main/java/seedu/address/model/ModelManager.java [hunk 1]
```diff
@@ -129,17 +131,15 @@ public ObservableList<Person> getFilteredPersonList() {
 
     @Override
     public void updateFilteredPersonList(Predicate<Person> predicate) {
-        requireNonNull(predicate);
-        filteredPersons.setPredicate(predicate);
-    }
+        updateFilteredPersonListHelper(predicate);
```
Comment (jon-seana) [inline src/main/java/seedu/address/model/ModelManager.java:134]: Well done on refactoring these two methods and combining it by removing unnecessary codes.

**Review by jon-seana — APPROVED** [review]
